# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QDockWidget, QHBoxLayout,
    QHeaderView, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QSpacerItem, QStatusBar, QTableWidget,
    QTableWidgetItem, QTextEdit, QToolBar, QToolButton,
    QVBoxLayout, QWidget)
from . import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1046, 708)
        MainWindow.setStyleSheet(u"/*  ------------------------------------------------------------------------  */\n"
"/* Qt-Material - https://github.com/dunderlab/qt-material\n"
"/* By Yeison Cardona - Dunderlab\n"
"/*  ------------------------------------------------------------------------  */\n"
"\n"
"\n"
"\n"
"\n"
"* {\n"
"  color: #555555;\n"
"  font-family: SF Pro;\n"
"  font-size: 12.0px;\n"
"  line-height: 5.0px;\n"
"  selection-background-color: #67daff;\n"
"  selection-color: #3c3c3c;\n"
"}\n"
"\n"
"*:focus {\n"
"   outline: none;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Custom colors  */\n"
"\n"
".danger {\n"
"  color: #dc3545;\n"
"  background-color: transparent;\n"
"}\n"
"\n"
".warning {\n"
"  color: #ffc107;\n"
"  background-color: transparent;\n"
"}\n"
"\n"
".success {\n"
"  color: #17a2b8;\n"
"  background-color: transparent;\n"
"}\n"
"\n"
".danger:disabled {\n"
"  color: rgba(220, 53, 69, 0.4);\n"
"  border-color: rgba(220, 53, 69, 0.4);\n"
"}\n"
"\n"
".warning:d"
                        "isabled {\n"
"  color: rgba(255, 193, 7, 0.4);\n"
"  border-color: rgba(255, 193, 7, 0.4);\n"
"}\n"
"\n"
".success:disabled {\n"
"  color: rgba(23, 162, 184, 0.4);\n"
"  border-color: rgba(23, 162, 184, 0.4);\n"
"}\n"
"\n"
".danger:flat:disabled {\n"
"  background-color: rgba(220, 53, 69, 0.1);\n"
"}\n"
"\n"
".warning:flat:disabled {\n"
"  background-color: rgba(255, 193, 7, 0.1);\n"
"}\n"
"\n"
".success:flat:disabled {\n"
"  background-color: rgba(23, 162, 184, 0.1);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Custom properties  */\n"
"\n"
"*[frameless=\"true\"] {\n"
"  border: none;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Basic widgets  */\n"
"\n"
"QWidget {\n"
"  background-color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #ffffff;\n"
"  border: 2px solid #e6e6e6;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QGroupBox.fill_background,\n"
"QFrame.fill_background"
                        " {\n"
"  background-color: #f5f5f5;\n"
"  border: 2px solid #f5f5f5;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QFrame[colored=\"true\"]{\n"
"  border: 2px solid #03a9f4;\n"
"}\n"
"\n"
"QFrame[colored=\"true\"]:disabled {\n"
"  border: 2px solid rgba(3, 169, 244, 0.1);\n"
"}\n"
"\n"
"QSplitter {\n"
"  background-color: transparent;\n"
"  border: none\n"
"}\n"
"\n"
"QStatusBar {\n"
"  color: #555555;\n"
"  background-color: rgba(230, 230, 230, 0.2);\n"
"  border-radius: 0px;\n"
"}\n"
"\n"
"QScrollArea,\n"
"QStackedWidget,\n"
"QWidget > QToolBox,\n"
"QToolBox > QWidget,\n"
"QTabWidget > QWidget {\n"
"  border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"  border: none;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Inputs  */\n"
"\n"
"QTextEdit,\n"
"QPushButton {\n"
"  color: #03a9f4;\n"
"  background-color: #ffffff;\n"
"  border: 2px solid #03a9f4;\n"
"  border-radius: 4px;\n"
"  height: 28px;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QTreeView,\n"
"QListView,\n"
"QCom"
                        "boBox {\n"
"  color: #3c3c3c;\n"
"  background-color: rgba(245, 245, 245, 0.75);\n"
"  padding-left: 12px;\n"
"  border-radius: 0px;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  height: 28px;\n"
"  border: 2px solid rgba(85, 85, 85, 0.2);\n"
"  border-width: 0 0 2px 0;\n"
"}\n"
"\n"
"QDateEdit,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #3c3c3c;\n"
"  background-color: rgba(245, 245, 245, 0.75);\n"
"  padding-left: 12px;\n"
"  border-radius: 0px;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  height: 28px;\n"
"  border: 2px solid rgba(85, 85, 85, 0.2);\n"
"  border-width: 0 0 2px 0;\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"  border-radius: 4px;\n"
"  padding: 4px 12px;\n"
"  background-color: #ffffff;\n"
"  border: 2px solid #e6e6e6;\n"
"}\n"
"\n"
"QTextEdit {\n"
"  padding: 4px 12px;\n"
"  border-radius: 4px;\n"
"  background-color: #f5f5f5;\n"
"}\n"
"\n"
"QPlainTextEdit:disabled {\n"
"  color: rgba(85, 85, 85, 0.4);\n"
"  backgr"
                        "ound-color: rgba(255, 255, 255, 0.2);\n"
"  border: 2px solid rgba(230, 230, 230, 0.2);\n"
"}\n"
"\n"
"QTextEdit:disabled {\n"
"  color: rgba(3, 169, 244, 0.4);\n"
"  background-color: #f5f5f5;\n"
"  border: 2px solid rgba(3, 169, 244, 0.2);\n"
"}\n"
"\n"
"QDateEdit:disabled,\n"
"QDateTimeEdit:disabled,\n"
"QSpinBox:disabled,\n"
"QDoubleSpinBox:disabled,\n"
"QLineEdit:disabled {\n"
"  color: rgba(85, 85, 85, 0.2);\n"
"  background-color: rgba(245, 245, 245, 0.3);\n"
"  border: 2px solid #f5f5f5;\n"
"  border-width: 0 0 2px 0;\n"
"  padding: 0px 12px;\n"
"  border-radius: 0px;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  height: 28px;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QComboBox  */\n"
"\n"
"QDateEdit,\n"
"QComboBox {\n"
"  color: #3c3c3c;\n"
"  border: 2px solid #03a9f4;\n"
"  border-radius: 0px;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  height: 28px;\n"
"  background-color: r"
                        "gba(245, 245, 245, 0.75);\n"
"  border: 2px solid rgba(85, 85, 85, 0.2);\n"
"  border-width: 0 0 2px 0;\n"
"}\n"
"\n"
"QDateEdit:disabled,\n"
"QComboBox:disabled {\n"
"  color: rgba(85, 85, 85, 0.2);\n"
"  background-color: rgba(245, 245, 245, 0.3);\n"
"  border-bottom: 2px solid #f5f5f5;\n"
"}\n"
"\n"
"QDateEdit::drop-down,\n"
"QComboBox::drop-down {\n"
"  border: none;\n"
"  color: #03a9f4;\n"
"  width: 20px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow,\n"
"QComboBox::down-arrow {\n"
"  image: url(:/icon/theme/active/downarrow.svg);\n"
"  margin-right: 8px;\n"
"}\n"
"\n"
"\n"
"QDateEdit::down-arrow:focus,\n"
"QComboBox::down-arrow:focus {\n"
"  image: url(:/icon/theme/primary/downarrow.svg);\n"
"  margin-right: 8px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:disabled,\n"
"QComboBox::down-arrow:disabled {\n"
"  image: url(:/icon/theme/disabled/downarrow.svg);\n"
"  margin-right: 8px;\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView,\n"
"QComboBox QAbstractItemView {\n"
"  background-color: #f5f5f5;\n"
"  border: 2px solid #e6e6"
                        "e6;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QDateEdit[frame='false'],\n"
"QComboBox[frame='false'] {\n"
"  color: #555555;\n"
"  background-color: transparent;\n"
"  border: 1px solid transparent;\n"
"}\n"
"\n"
"QDateEdit[frame='false']:disabled,\n"
"QComboBox[frame='false']:disabled {\n"
"  color: rgba(85, 85, 85, 0.2);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Spin buttons  */\n"
"\n"
"QDateTimeEdit::up-button,\n"
"QDoubleSpinBox::up-button,\n"
"QSpinBox::up-button {\n"
"  subcontrol-origin: border;\n"
"  subcontrol-position: top right;\n"
"  width: 20px;\n"
"  image: url(:/icon/theme/active/uparrow.svg);\n"
"  border-width: 0px;\n"
"  margin-right: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-button:disabled,\n"
"QDoubleSpinBox::up-button:disabled,\n"
"QSpinBox::up-button:disabled {\n"
"  image: url(:/icon/theme/disabled/uparrow.svg);\n"
"}\n"
"\n"
"QDateTimeEdit::down-button,\n"
"QDoubleSpinBox::down-button,\n"
"QSpinBox::down-button {\n"
"  subcontro"
                        "l-origin: border;\n"
"  subcontrol-position: bottom right;\n"
"  width: 20px;\n"
"  image: url(:/icon/theme/active/downarrow.svg);\n"
"  border-width: 0px;\n"
"  border-top-width: 0;\n"
"  margin-right: 5px;\n"
"}\n"
"\n"
"QDateTimeEdit::down-button:disabled,\n"
"QDoubleSpinBox::down-button:disabled,\n"
"QSpinBox::down-button:disabled {\n"
"  image: url(:/icon/theme/disabled/downarrow.svg);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QPushButton  */\n"
"\n"
"QPushButton {\n"
"  text-transform: uppercase;\n"
"  margin: 0px;\n"
"  padding: 4px 12px;\n"
"  height: 28px;\n"
"  font-weight: bold;\n"
"\n"
"  \n"
"    border-radius: 4px;\n"
"  \n"
"}\n"
"\n"
"QPushButton:checked,\n"
"QPushButton:pressed {\n"
"  color: #ffffff;\n"
"  background-color: #03a9f4;\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"  margin: 0px;\n"
"  color: #03a9f4;\n"
"  border: none;\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"QPushButton:flat:hover {\n"
"  background-color: rgba(3"
                        ", 169, 244, 0.1);\n"
"}\n"
"\n"
"QPushButton:flat:pressed,\n"
"QPushButton:flat:checked {\n"
"  background-color: rgba(3, 169, 244, 0.1);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"  color: rgba(230, 230, 230, 0.75);\n"
"  background-color: transparent;\n"
"  border: 2px solid rgba(230, 230, 230, 0.75);\n"
"}\n"
"\n"
"QPushButton:flat:disabled {\n"
"  color: rgba(230, 230, 230, 0.75);\n"
"  background-color: rgba(230, 230, 230, 0.25);\n"
"  border: none;\n"
"}\n"
"\n"
"QPushButton:checked:disabled {\n"
"  color: #f5f5f5;\n"
"  background-color: #e6e6e6;\n"
"  border-color:  #e6e6e6;\n"
"}\n"
"\n"
"QToolButton:focus,\n"
"QPushButton:focus {\n"
"  background-color: rgba(3, 169, 244, 0.2);\n"
"}\n"
"\n"
"QPushButton:checked:focus,\n"
"QPushButton:pressed:focus {\n"
"  background-color: rgba(3, 169, 244, 0.8);\n"
"}\n"
"\n"
"QPushButton:flat:focus {\n"
"  border: none;\n"
"  background-color: rgba(3, 169, 244, 0.2);\n"
"}\n"
"\n"
"\n"
"/*  ------------------------------------------------------------------------  */"
                        "\n"
"/*  QTabBar  */\n"
"\n"
"QTabBar{\n"
"  text-transform: uppercase;\n"
"  font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  color: #555555;\n"
"  border: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom,\n"
"QTabBar::tab:top{\n"
"  padding: 0 12px;\n"
"  height: 24px;\n"
"}\n"
"\n"
"QTabBar::tab:left,\n"
"QTabBar::tab:right{\n"
"  padding: 12px 0;\n"
"  width: 24px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected,\n"
"QTabBar::tab:top:hover {\n"
"  color: #03a9f4;\n"
"  border-bottom: 2px solid #03a9f4;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected,\n"
"QTabBar::tab:bottom:hover {\n"
"  color: #03a9f4;\n"
"  border-top: 2px solid #03a9f4;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected,\n"
"QTabBar::tab:right:hover {\n"
"  color: #03a9f4;\n"
"  border-left: 2px solid #03a9f4;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected,\n"
"QTabBar::tab:left:hover {\n"
"  color: #03a9f4;\n"
"  border-right: 2px solid #03a9f4;\n"
"}\n"
"\n"
"QTabBar QToolButton:hover,\n"
"QTabBar QToolButton {\n"
"  border: 0px;\n"
"  background-color: #f5f5f5"
                        ";\n"
"  background: #f5f5f5;\n"
"}\n"
"\n"
"QTabBar QToolButton::up-arrow {\n"
"  image: url(:/icon/theme/primary/uparrow2.svg);\n"
"  width: 24px;\n"
"}\n"
"\n"
"QTabBar QToolButton::down-arrow {\n"
"  image: url(:/icon/theme/primary/downarrow2.svg);\n"
"  width: 24px;\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow {\n"
"  image: url(:/icon/theme/disabled/rightarrow2.svg);\n"
"  height: 24px;\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow {\n"
"  image: url(:/icon/theme/disabled/leftarrow2.svg);\n"
"  height: 24px;\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"  image: url(:/icon/theme/primary/tab_close.svg);\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"  image: url(:/icon/theme/primary/tab_close.svg);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QGroupBox  */\n"
"\n"
"QGroupBox {\n"
"  padding: 12px;\n"
"  padding-top: 32px;\n"
"  line-height: 13px;\n"
"  text-transform: uppercase;\n"
"  font-size: 13px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  colo"
                        "r: rgba(85, 85, 85, 0.4);\n"
"  subcontrol-origin: margin;\n"
"  subcontrol-position: top left;\n"
"  padding: 12px;\n"
"  background-color: transparent;\n"
"  height: 32px;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QRadioButton and QCheckBox labels  */\n"
"\n"
"QRadioButton,\n"
"QCheckBox {\n"
"  color: #555555;\n"
"  line-height: 14px;\n"
"  height: 32px;\n"
"  background-color: transparent;\n"
"  spacing: 5px;\n"
"}\n"
"\n"
"QRadioButton:disabled,\n"
"QCheckBox:disabled {\n"
"  color: rgba(85, 85, 85, 0.3);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  General Indicators  */\n"
"\n"
"QGroupBox::indicator {\n"
"  width: 20px;\n"
"  height: 20px;\n"
"  border-radius: 3px;\n"
"}\n"
"\n"
"QMenu::indicator,\n"
"QListView::indicator,\n"
"QTableWidget::indicator,\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 24px;\n"
"  height: 24px;\n"
"  border-radius: 4px;\n"
" }\n"
"\n"
""
                        "/*  ------------------------------------------------------------------------  */\n"
"/*  QListView Indicator  */\n"
"\n"
"QListView::indicator:checked,\n"
"QListView::indicator:checked:selected,\n"
"QListView::indicator:checked:focus {\n"
"  image: url(:/icon/theme/primary/checklist.svg);\n"
"}\n"
"\n"
"QListView::indicator:checked:selected:active {\n"
"  image: url(:/icon/theme/primary/checklist_invert.svg);\n"
"}\n"
"\n"
"QListView::indicator:checked:disabled {\n"
"  image: url(:/icon/theme/disabled/checklist.svg);\n"
"}\n"
"\n"
"QListView::indicator:indeterminate,\n"
"QListView::indicator:indeterminate:selected,\n"
"QListView::indicator:indeterminate:focus {\n"
"  image: url(:/icon/theme/primary/checklist_indeterminate.svg);\n"
"}\n"
"\n"
"QListView::indicator:indeterminate:selected:active {\n"
"  image: url(:/icon/theme/primary/checklist_indeterminate_invert.svg);\n"
"}\n"
"\n"
"QListView::indicator:indeterminate:disabled {\n"
"  image: url(:/icon/theme/disabled/checklist_indeterminate.svg);\n"
"}\n"
"\n"
""
                        "/*  ------------------------------------------------------------------------  */\n"
"/*  QTableView Indicator  */\n"
"\n"
"QTableView::indicator:enabled:checked,\n"
"QTableView::indicator:enabled:checked:selected,\n"
"QTableView::indicator:enabled:checked:focus {\n"
"  image: url(:/icon/theme/primary/checkbox_checked.svg);\n"
"}\n"
"\n"
"QTableView::indicator:checked:selected:active {\n"
"  image: url(:/icon/theme/primary/checkbox_checked_invert.svg);\n"
"}\n"
"\n"
"QTableView::indicator:disabled:checked,\n"
"QTableView::indicator:disabled:checked:selected,\n"
"QTableView::indicator:disabled:checked:focus {\n"
"  image: url(:/icon/theme/disabled/checkbox_checked.svg);\n"
"}\n"
"\n"
"QTableView::indicator:enabled:unchecked,\n"
"QTableView::indicator:enabled:unchecked:selected,\n"
"QTableView::indicator:enabled:unchecked:focus {\n"
"  image: url(:/icon/theme/primary/checkbox_unchecked.svg);\n"
"}\n"
"\n"
"QTableView::indicator:unchecked:selected:active {\n"
"  image: url(:/icon/theme/primary/checkbox_unchecked_i"
                        "nvert.svg);\n"
"}\n"
"\n"
"QTableView::indicator:disabled:unchecked,\n"
"QTableView::indicator:disabled:unchecked:selected,\n"
"QTableView::indicator:disabled:unchecked:focus {\n"
"  image: url(:/icon/theme/disabled/checkbox_unchecked.svg);\n"
"}\n"
"\n"
"QTableView::indicator:enabled:indeterminate,\n"
"QTableView::indicator:enabled:indeterminate:selected,\n"
"QTableView::indicator:enabled:indeterminate:focus {\n"
"  image: url(:/icon/theme/primary/checkbox_indeterminate.svg);\n"
"}\n"
"\n"
"QTableView::indicator:indeterminate:selected:active {\n"
"  image: url(:/icon/theme/primary/checkbox_indeterminate_invert.svg);\n"
"}\n"
"\n"
"QTableView::indicator:disabled:indeterminate,\n"
"QTableView::indicator:disabled:indeterminate:selected,\n"
"QTableView::indicator:disabled:indeterminate:focus {\n"
"  image: url(:/icon/theme/disabled/checkbox_indeterminate.svg);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QCheckBox and QGroupBox Indicator  */\n"
"\n"
"QChe"
                        "ckBox::indicator:checked,\n"
"QGroupBox::indicator:checked {\n"
"  image: url(:/icon/theme/primary/checkbox_checked.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked,\n"
"QGroupBox::indicator:unchecked {\n"
"  image: url(:/icon/theme/primary/checkbox_unchecked.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate,\n"
"QGroupBox::indicator:indeterminate {\n"
"  image: url(:/icon/theme/primary/checkbox_indeterminate.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled,\n"
"QGroupBox::indicator:checked:disabled {\n"
"  image: url(:/icon/theme/disabled/checkbox_checked.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:disabled,\n"
"QGroupBox::indicator:unchecked:disabled {\n"
"  image: url(:/icon/theme/disabled/checkbox_unchecked.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:disabled,\n"
"QGroupBox::indicator:indeterminate:disabled {\n"
"  image: url(:/icon/theme/disabled/checkbox_indeterminate.svg);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  "
                        "*/\n"
"/*  QRadioButton Indicator  */\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  image: url(:/icon/theme/primary/radiobutton_checked.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  image: url(:/icon/theme/primary/radiobutton_unchecked.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:disabled {\n"
"  image: url(:/icon/theme/disabled/radiobutton_checked.svg);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:disabled {\n"
"  image: url(:/icon/theme/disabled/radiobutton_unchecked.svg);\n"
"}\n"
"\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QDockWidget  */\n"
"\n"
"QDockWidget {\n"
"  color: #555555;\n"
"  text-transform: uppercase;\n"
"  border: 2px solid #f5f5f5;\n"
"  titlebar-close-icon: url(:/icon/theme/primary/close.svg);\n"
"  titlebar-normal-icon: url(:/icon/theme/primary/float.svg);\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"  text-align: left;\n"
"  padding-left: 32px;\n"
"  padding: 3px;\n"
"  margin-top"
                        ": 4px;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QComboBox indicator  */\n"
"\n"
"QComboBox::indicator:checked {\n"
"  image: url(:/icon/theme/primary/checklist.svg);\n"
"}\n"
"\n"
"QComboBox::indicator:checked:selected {\n"
"  image: url(:/icon/theme/primary/checklist_invert.svg);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Menu Items  */\n"
"\n"
"QComboBox::item,\n"
"QCalendarWidget QMenu::item,\n"
"QMenu::item {\n"
"  \n"
"    height: 24px;\n"
"  \n"
"  border: 8px solid transparent;\n"
"  color: #555555;\n"
"}\n"
"\n"
"QCalendarWidget QMenu::item,\n"
"QMenu::item {\n"
"  \n"
"    \n"
"      padding: 0px 20px 0px 8px;  /* pyside6 or pyqt6 */\n"
"    \n"
"  \n"
"}\n"
"\n"
"\n"
"QComboBox::item:selected,\n"
"QCalendarWidget QMenu::item:selected,\n"
"QMenu::item:selected {\n"
"  color: #3c3c3c;\n"
"  background-color: #67daff;\n"
"  border-radius: 0px;\n"
"}\n"
"\n"
"QComboBox::item:disable"
                        "d,\n"
"QCalendarWidget QMenu::item:disabled,\n"
"QMenu::item:disabled {\n"
"  color: rgba(85, 85, 85, 0.3);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QMenu  */\n"
"\n"
"QCalendarWidget QMenu,\n"
"QMenu {\n"
"  background-color: #f5f5f5;\n"
"  border: 2px solid #e6e6e6;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"  height: 2px;\n"
"  background-color: #e6e6e6;\n"
"  margin-left: 2px;\n"
"  margin-right: 2px;\n"
"}\n"
"\n"
"QMenu::right-arrow{\n"
"  image: url(:/icon/theme/primary/rightarrow.svg);\n"
"  width: 12px;\n"
"  height: 12px;\n"
"}\n"
"\n"
"QMenu::right-arrow:selected{\n"
"  image: url(:/icon/theme/disabled/rightarrow.svg);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked {\n"
"  image: url(:/icon/theme/primary/checkbox_unchecked.svg);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:selected {\n"
"  image: url(:/icon/theme/primary/checkbox_unchecked_invert.svg);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive"
                        ":checked {\n"
"  image: url(:/icon/theme/primary/checkbox_checked.svg);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:selected {\n"
"  image: url(:/icon/theme/primary/checkbox_checked_invert.svg);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked {\n"
"  image: url(:/icon/theme/primary/radiobutton_unchecked.svg);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:selected {\n"
"  image: url(:/icon/theme/primary/radiobutton_unchecked_invert.svg);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked {\n"
"  image: url(:/icon/theme/primary/radiobutton_checked.svg);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:selected {\n"
"  image: url(:/icon/theme/primary/radiobutton_checked_invert.svg);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QMenuBar  */\n"
"\n"
"QMenuBar {\n"
"  background-color: #f5f5f5;\n"
"  color: #555555;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"  height: 28px;\n"
"  padding: 8px;\n"
"  background-color: transparent;\n"
"  color: #5"
                        "55555;\n"
"}\n"
"\n"
"QMenuBar::item:selected,\n"
"QMenuBar::item:pressed {\n"
"  color: #3c3c3c;\n"
"  background-color: #67daff;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QToolBox  */\n"
"\n"
"QToolBox::tab {\n"
"  background-color: #f5f5f5;\n"
"  color: #555555;\n"
"  text-transform: uppercase;\n"
"  border-radius: 4px;\n"
"  padding-left: 15px;\n"
"}\n"
"\n"
"QToolBox::tab:selected,\n"
"QToolBox::tab:hover {\n"
"  background-color: rgba(3, 169, 244, 0.2);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QProgressBar  */\n"
"\n"
"QProgressBar {\n"
"  border-radius: 0;\n"
"  background-color: #e6e6e6;\n"
"  text-align: center;\n"
"  color: transparent;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"  background-color: #03a9f4;\n"
"}\n"
"\n"
"QProgressBar:disabled {\n"
"  background-color: #f5f5f5;\n"
"}\n"
"\n"
"QProgressBar::chunk:disabled {\n"
"  background-color: rgba(3, 169, 244, 0.1);\n"
"}\n"
""
                        "\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QScrollBar  */\n"
"\n"
"QScrollBar:horizontal {\n"
"  border: 0;\n"
"  background: #f5f5f5;\n"
"  height: 4px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"  border: 0;\n"
"  background: #f5f5f5;\n"
"  width: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"  background: rgba(3, 169, 244, 0.3);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"  min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"  background: #03a9f4;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"  border: 0;\n"
"  background: transparent;\n"
"  width: 0px;\n"
"  height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page"
                        ":vertical,\n"
"QScrolLBar:vertical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar:disabled {\n"
"    background: rgba(245, 245, 245, 0.4);\n"
"}\n"
"\n"
"QScrollBar::handle:disabled {\n"
"    background: rgba(3, 169, 244, 0.1);\n"
"}\n"
"\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QScrollBar-Big  */\n"
"\n"
"QScrollBar.big:horizontal {\n"
"  border: 0;\n"
"  background: #f5f5f5;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QScrollBar.big:vertical {\n"
"  border: 0;\n"
"  background: #f5f5f5;\n"
"  width: 32px;\n"
"}\n"
"\n"
"QScrollBar.big::handle,\n"
"QScrollBar.big::handle:vertical:hover,\n"
"QScrollBar.big::handle:horizontal:hover {\n"
"  background: #03a9f4;\n"
"}\n"
"\n"
"QScrollBar.big::handle:horizontal {\n"
"  min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar.big::handle:vertical {\n"
"  min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar.big::add-line:vertical,\n"
"QScrollBar.big::sub-line:vertical,\n"
"QScrollBar.big::add-line:horizontal,\n"
"QScrollBar.big"
                        "::sub-line:horizontal {\n"
"  border: 0;\n"
"  background: transparent;\n"
"  width: 0px;\n"
"  height: 0px;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QSlider  */\n"
"\n"
"QSlider:horizontal {\n"
"  min-height: 20px;\n"
"  max-height: 20px;\n"
"}\n"
"\n"
"QSlider:vertical {\n"
"  min-width: 20px;\n"
"  max-width: 20px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"  height: 4px;\n"
"  margin: 0 8px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"  width: 4px;\n"
"  margin: 8px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"  image: url(:/icon/theme/primary/slider.svg);\n"
"  width: 14px;\n"
"  height: 14px;\n"
"  margin: -14px -5px;\n"
"}\n"
"\n"
"QSlider::handle {\n"
"  image: url(:/icon/theme/primary/slider.svg);\n"
"  width: 14px;\n"
"  height: 14px;\n"
"  margin: -5px -14px;\n"
"}\n"
"\n"
"QSlider::add-page {\n"
"background: #f5f5f5;\n"
"}\n"
"\n"
"QSlider::sub-page {\n"
"background: #03a9f4;\n"
"}\n"
"\n"
"QSlider::handle:vertical:disabled"
                        ",\n"
"QSlider::handle:horizontal:disabled {\n"
"  image: url(:/icon/theme/disabled/slider.svg);\n"
"}\n"
"\n"
"QSlider::sub-page:disabled {\n"
"background: #e6e6e6;\n"
"}\n"
"\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QLabel  */\n"
"\n"
"QLabel {\n"
"  border: none;\n"
"  background: transparent;\n"
"  color: #555555\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"  color: rgba(85, 85, 85, 0.3)\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  VLines and HLinex  */\n"
"\n"
"QFrame[frameShape=\"4\"] {\n"
"    border-width: 1px 0 0 0;\n"
"    background: none;\n"
"}\n"
"\n"
"QFrame[frameShape=\"5\"] {\n"
"    border-width: 0 1px 0 0;\n"
"    background: none;\n"
"}\n"
"\n"
"QFrame[frameShape=\"4\"],\n"
"QFrame[frameShape=\"5\"] {\n"
"  border-color: #e6e6e6;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QToolBar  */\n"
"\n"
"QToolBar {\n"
"  background: #fff"
                        "fff;\n"
"  border: 0px solid;\n"
"}\n"
"\n"
"QToolBar:horizontal {\n"
"  border-bottom: 1px solid #e6e6e6;\n"
"}\n"
"\n"
"QToolBar:vertical {\n"
"  border-right: 1px solid #e6e6e6;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"  image: url(:/icon/theme/primary/toolbar-handle-horizontal.svg);\n"
"}\n"
"\n"
"QToolBar::handle:vertical {\n"
"  image: url(:/icon/theme/primary/toolbar-handle-vertical.svg);\n"
"}\n"
"\n"
"QToolBar::separator:horizontal {\n"
"  border-right: 1px solid #e6e6e6;\n"
"  border-left: 1px solid #e6e6e6;\n"
"  width: 1px;\n"
"}\n"
"\n"
"QToolBar::separator:vertical {\n"
"  border-top: 1px solid #e6e6e6;\n"
"  border-bottom: 1px solid #e6e6e6;\n"
"  height: 1px;\n"
"}\n"
"\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QToolButton  */\n"
"\n"
"QToolButton {\n"
"  background: #ffffff;\n"
"  border: 0px;\n"
"  height: 32px;\n"
"  margin: 3px;\n"
"  padding: 3px;\n"
"  border-right: 12px solid #ffffff;\n"
"  border-left: 12px solid #ffffff;\n"
""
                        "}\n"
"\n"
"QToolButton:hover {\n"
"  background: #e6e6e6;\n"
"  border-right: 12px solid #e6e6e6;\n"
"  border-left: 12px solid #e6e6e6;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"  background: #f5f5f5;\n"
"  border-right: 12px solid #f5f5f5;\n"
"  border-left: 12px solid #f5f5f5;\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"  background: #e6e6e6;\n"
"  border-left: 12px solid #e6e6e6;\n"
"  border-right: 12px solid #03a9f4;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  General viewers  */\n"
"\n"
"QTableView {\n"
"  background-color: #ffffff;\n"
"  border: 1px solid #f5f5f5;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView {\n"
"  border-radius: 4px;\n"
"  padding: 4px;\n"
"  margin: 0px;\n"
"  border: 0px;\n"
"}\n"
"\n"
"QTableView::item,\n"
"QTreeView::item,\n"
"QListView::item {\n"
"  padding: 4px;\n"
"  min-height: 28px;\n"
"  color: #555555;\n"
"  selection-color: #555555; /* For Windows */\n"
"  border-color: transparent;  /* Fix #34 *"
                        "/\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Items Selection */\n"
"\n"
"QTableView::item:selected,\n"
"QTreeView::item:selected,\n"
"QListView::item:selected {\n"
"  background-color: rgba(3, 169, 244, 0.2);\n"
"  selection-background-color: rgba(3, 169, 244, 0.2);\n"
"  color: #555555;\n"
"  selection-color: #555555; /* For Windows */\n"
"}\n"
"\n"
"QTableView::item:selected:focus,\n"
"QTreeView::item:selected:focus,\n"
"QListView::item:selected:focus {\n"
"  background-color: #03a9f4;\n"
"  selection-background-color: #03a9f4;\n"
"  color: #3c3c3c;\n"
"  selection-color: #3c3c3c; /* For Windows */\n"
"}\n"
"\n"
"QListView,\n"
"QTreeView,\n"
"QTableView {\n"
"  selection-background-color: rgba(3, 169, 244, 0.2);\n"
"  alternate-background-color: rgba(3, 169, 244, 0.1);\n"
"}\n"
"\n"
"QTableView:focus {\n"
"  selection-background-color: #03a9f4;\n"
"}\n"
"\n"
"QTableView::item:disabled {\n"
"  color: rgba(85, 85, 85, 0.3);\n"
"  selection-color: rgb"
                        "a(85, 85, 85, 0.3);\n"
"  background-color: #f5f5f5;\n"
"  selection-background-color: #f5f5f5;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QTreeView  */\n"
"\n"
"QTreeView::branch{\n"
"  background-color: #f5f5f5;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings,\n"
"QTreeView::branch:closed:has-children:!has-siblings {\n"
"  image: url(:/icon/theme/primary/branch-closed.svg);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings {\n"
"  image: url(:/icon/theme/primary/branch-open.svg);\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"  border-image: url(:/icon/theme/disabled/vline.svg) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(:/icon/theme/disabled/branch-more.svg) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item,\n"
"QTreeView::branch:has-children:!has-siblings:adjoins-item {\n"
""
                        "    border-image: url(:/icon/theme/disabled/branch-end.svg) 0;\n"
"}\n"
"\n"
"QTreeView QHeaderView::section {\n"
"  border: none;\n"
"}\n"
"\n"
"QListView:disabled,\n"
"QTreeView:disabled {\n"
"  background-color: rgba(230, 230, 230, 0.5);\n"
"}\n"
"\n"
"QListView::item:disabled,\n"
"QTreeView::item:disabled {\n"
"  color: rgba(85, 85, 85, 0.2);\n"
"  selection-color: rgba(85, 85, 85, 0.2); /* For Windows */\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings:disabled,\n"
"QTreeView::branch:closed:has-children:!has-siblings:disabled {\n"
"  image: url(:/icon/theme/disabled/branch-closed.svg);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings:disabled,\n"
"QTreeView::branch:open:has-children:has-siblings:disabled {\n"
"  image: url(:/icon/theme/disabled/branch-open.svg);\n"
"}\n"
"\n"
"QTreeView QHeaderView::section:disabled {\n"
"  color: rgba(85, 85, 85, 0.2);\n"
"  selection-color: rgba(85, 85, 85, 0.2); /* For Windows */\n"
"}\n"
"\n"
"QListView::item:selected:disabled,\n"
"QLi"
                        "stView::item:selected:focus:disabled,\n"
"QTreeView::item:selected:disabled,\n"
"QTreeView::item:selected:focus:disabled {\n"
"  background-color: rgba(3, 169, 244, 0.1);\n"
"  selection-background-color: rgba(3, 169, 244, 0.1);\n"
"  color: rgba(60, 60, 60, 0.1);\n"
"  selection-color: rgba(60, 60, 60, 0.1); /* For Windows */\n"
"}\n"
"\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Custom buttons  */\n"
"\n"
"QPushButton.danger {\n"
"  border-color: #dc3545;\n"
"  color: #dc3545;\n"
"}\n"
"\n"
"QPushButton.danger:checked,\n"
"QPushButton.danger:pressed {\n"
"  color: #ffffff;\n"
"  background-color: #dc3545;\n"
"}\n"
"\n"
"QPushButton.warning{\n"
"  border-color: #ffc107;\n"
"  color: #ffc107;\n"
"}\n"
"\n"
"QPushButton.warning:checked,\n"
"QPushButton.warning:pressed {\n"
"  color: #ffffff;\n"
"  background-color: #ffc107;\n"
"}\n"
"\n"
"QPushButton.success {\n"
"  border-color: #17a2b8;\n"
"  color: #17a2b8;\n"
"}\n"
"\n"
"QPushButton.success:checked,\n"
""
                        "QPushButton.success:pressed {\n"
"  color: #ffffff;\n"
"  background-color: #17a2b8;\n"
"}\n"
"\n"
"QPushButton.danger:flat:hover {\n"
"  background-color: rgba(220, 53, 69, 0.2);\n"
"}\n"
"\n"
"QPushButton.danger:flat:pressed,\n"
"QPushButton.danger:flat:checked {\n"
"  background-color: rgba(220, 53, 69, 0.1);\n"
"  color: #dc3545;\n"
"}\n"
"\n"
"QPushButton.warning:flat:hover {\n"
"  background-color: rgba(255, 193, 7, 0.2);\n"
"}\n"
"\n"
"QPushButton.warning:flat:pressed,\n"
"QPushButton.warning:flat:checked {\n"
"  background-color: rgba(255, 193, 7, 0.1);\n"
"  color: #ffc107;\n"
"}\n"
"\n"
"QPushButton.success:flat:hover {\n"
"  background-color: rgba(23, 162, 184, 0.2);\n"
"}\n"
"\n"
"QPushButton.success:flat:pressed,\n"
"QPushButton.success:flat:checked {\n"
"  background-color: rgba(23, 162, 184, 0.1);\n"
"  color: #17a2b8;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QTableView  */\n"
"\n"
"QTableCornerButton::section {\n"
"  background-colo"
                        "r: #f5f5f5;\n"
"  border-radius: 0px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color: #ffffff;\n"
"}\n"
"\n"
"QHeaderView {\n"
"  border: none;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"  color: rgba(85, 85, 85, 0.7);\n"
"  text-transform: uppercase;\n"
"  background-color: #f5f5f5;\n"
"  padding: 0 20px;\n"
"  height: 32px;\n"
"  border-radius: 0px;\n"
"  border-right: 1px solid;\n"
"  border-bottom: 1px solid;\n"
"  border-color: #ffffff;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QLCDNumber  */\n"
"\n"
"QLCDNumber {\n"
"  color: #03a9f4;\n"
"  background-color:rgba(3, 169, 244, 0.1);\n"
"  border: 1px solid rgba(3, 169, 244, 0.3);\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QLCDNumber:disabled  {\n"
"  color: #e6e6e6;\n"
"  background-color: rgba(230, 230, 230, 0.4);\n"
"  border: 1px solid rgba(230, 230, 230, 0"
                        ".3);\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/* QDial */\n"
"QDial {\n"
"\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QCalendarWidget  */\n"
"\n"
"QCalendarWidget {\n"
"  min-height: 300px;\n"
"}\n"
"\n"
"#qt_calendar_prevmonth {\n"
"  qproperty-icon: url(:/icon/theme/primary/leftarrow.svg);\n"
"}\n"
"\n"
"#qt_calendar_nextmonth {\n"
"  qproperty-icon: url(:/icon/theme/primary/rightarrow.svg);\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Inline QLineEdit  */\n"
"\n"
"QTreeView QLineEdit,\n"
"QTableView QLineEdit,\n"
"QListView QLineEdit {\n"
"  color: #555555;\n"
"  background-color: #f5f5f5;\n"
"  border: 1px solid unset;\n"
"  border-radius: unset;\n"
"  padding: unset;\n"
"  padding-left: unset;\n"
"  height: unset;\n"
"  border-width: unset;\n"
"  border-top-left-radius: unset;\n"
"  border-top-right"
                        "-radius: unset;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QToolTip  */\n"
"\n"
"QToolTip {\n"
"  padding: 4px;\n"
"  border: 1px solid #ffffff;\n"
"  border-radius: 4px;\n"
"  color: #555555;\n"
"  background-color: #e6e6e6;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  QDialog  */\n"
"\n"
"\n"
"\n"
"QDialog QToolButton:disabled {\n"
"  background-color: #f5f5f5;\n"
"  color: #555555\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Grips  */\n"
"\n"
"\n"
"QMainWindow::separator:vertical,\n"
"QSplitter::handle:horizontal {\n"
"  image: url(:/icon/theme/primary/splitter-horizontal.svg);\n"
"}\n"
"\n"
"QMainWindow::separator:horizontal,\n"
"QSplitter::handle:vertical {\n"
"  image: url(:/icon/theme/primary/splitter-vertical.svg);\n"
"}\n"
"\n"
"QSizeGrip {\n"
"  image: url(:/icon/theme/primary/sizegrip.svg);\n"
"  background-color: transpare"
                        "nt;\n"
"}\n"
"\n"
"QMenuBar QToolButton:hover,\n"
"QMenuBar QToolButton:pressed,\n"
"QMenuBar QToolButton {\n"
"  border-width: 0;\n"
"  border-left: 10px;\n"
"  border-image: url(:/icon/theme/primary/rightarrow2.svg);\n"
"  background-color: transparent;\n"
"}\n"
"\n"
"/*  ------------------------------------------------------------------------  */\n"
"/*  Focus  */\n"
"\n"
"QDateTimeEdit:focus,\n"
"QSpinBox:focus,\n"
"QDoubleSpinBox:focus,\n"
"QLineEdit:focus,\n"
"QComboBox:focus {\n"
"  color: #03a9f4;\n"
"  border: 2px solid #03a9f4;\n"
"  border-width: 0 0 2px 0;\n"
"\n"
"}\n"
"\n"
"QDateTimeEdit::up-button:focus,\n"
"QDoubleSpinBox::up-button:focus,\n"
"QSpinBox::up-button:focus {\n"
"  image: url(:/icon/theme/primary/uparrow.svg);\n"
"}\n"
"\n"
"QDateTimeEdit::down-button:focus,\n"
"QDoubleSpinBox::down-button:focus,\n"
"QSpinBox::down-button:focus {\n"
"  image: url(:/icon/theme/primary/downarrow.svg);\n"
"}\n"
"\n"
"QMenu::indicator:focus,\n"
"QListView::indicator:focus,\n"
"QTableWidget::indicator:fo"
                        "cus,\n"
"QRadioButton::indicator:focus {\n"
"  background-color: rgba(3, 169, 244, 0.2);\n"
"  border-radius: 10px;\n"
" }\n"
"\n"
"QCheckBox::indicator:focus {\n"
"  background-color: rgba(3, 169, 244, 0.2);\n"
" }")
        MainWindow.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks)
        self.add_wpt_action = QAction(MainWindow)
        self.add_wpt_action.setObjectName(u"add_wpt_action")
        icon = QIcon()
        icon.addFile(u":/gis/gis/plus.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.add_wpt_action.setIcon(icon)
        self.add_wpt_action.setMenuRole(QAction.MenuRole.NoRole)
        self.delete_wpt_action = QAction(MainWindow)
        self.delete_wpt_action.setObjectName(u"delete_wpt_action")
        self.delete_wpt_action.setMenuRole(QAction.MenuRole.NoRole)
        self.toggle_debug_log_action = QAction(MainWindow)
        self.toggle_debug_log_action.setObjectName(u"toggle_debug_log_action")
        self.toggle_debug_log_action.setCheckable(True)
        self.toggle_debug_log_action.setMenuRole(QAction.MenuRole.NoRole)
        self.scan_for_devices_action = QAction(MainWindow)
        self.scan_for_devices_action.setObjectName(u"scan_for_devices_action")
        self.scan_for_devices_action.setCheckable(True)
        self.scan_for_devices_action.setMenuRole(QAction.MenuRole.NoRole)
        self.import_file_action = QAction(MainWindow)
        self.import_file_action.setObjectName(u"import_file_action")
        icon1 = QIcon()
        icon1.addFile(u":/gis/gis/import_locations.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.import_file_action.setIcon(icon1)
        self.import_file_action.setMenuRole(QAction.MenuRole.NoRole)
        self.download_locations_fit_action = QAction(MainWindow)
        self.download_locations_fit_action.setObjectName(u"download_locations_fit_action")
        self.download_locations_fit_action.setEnabled(False)
        icon2 = QIcon()
        icon2.addFile(u":/gis/gis/download.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.download_locations_fit_action.setIcon(icon2)
        self.download_locations_fit_action.setMenuRole(QAction.MenuRole.NoRole)
        self.upload_locations_fit_action = QAction(MainWindow)
        self.upload_locations_fit_action.setObjectName(u"upload_locations_fit_action")
        self.upload_locations_fit_action.setEnabled(False)
        icon3 = QIcon()
        icon3.addFile(u":/gis/gis/upload_device.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.upload_locations_fit_action.setIcon(icon3)
        self.upload_locations_fit_action.setMenuRole(QAction.MenuRole.NoRole)
        self.save_file_action = QAction(MainWindow)
        self.save_file_action.setObjectName(u"save_file_action")
        icon4 = QIcon()
        icon4.addFile(u":/gis/gis/save_file.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.save_file_action.setIcon(icon4)
        self.save_file_action.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_3 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.waypoint_table = QTableWidget(self.centralwidget)
        if (self.waypoint_table.columnCount() < 7):
            self.waypoint_table.setColumnCount(7)
        self.waypoint_table.setObjectName(u"waypoint_table")
        self.waypoint_table.setEditTriggers(QAbstractItemView.EditTrigger.DoubleClicked|QAbstractItemView.EditTrigger.EditKeyPressed|QAbstractItemView.EditTrigger.SelectedClicked)
        self.waypoint_table.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.waypoint_table.setIconSize(QSize(24, 24))
        self.waypoint_table.setShowGrid(False)
        self.waypoint_table.setCornerButtonEnabled(False)
        self.waypoint_table.setColumnCount(7)
        self.waypoint_table.horizontalHeader().setVisible(True)
        self.waypoint_table.horizontalHeader().setHighlightSections(False)
        self.waypoint_table.horizontalHeader().setStretchLastSection(True)
        self.waypoint_table.verticalHeader().setVisible(False)
        self.waypoint_table.verticalHeader().setMinimumSectionSize(40)

        self.verticalLayout_2.addWidget(self.waypoint_table)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.delete_wpt_btn = QToolButton(self.centralwidget)
        self.delete_wpt_btn.setObjectName(u"delete_wpt_btn")
        icon5 = QIcon()
        icon5.addFile(u":/gis/gis/minus.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.delete_wpt_btn.setIcon(icon5)

        self.horizontalLayout.addWidget(self.delete_wpt_btn)

        self.add_wpt_btn = QToolButton(self.centralwidget)
        self.add_wpt_btn.setObjectName(u"add_wpt_btn")
        icon6 = QIcon()
        icon6.addFile(u":/gis/gis/plus.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.add_wpt_btn.setIcon(icon6)

        self.horizontalLayout.addWidget(self.add_wpt_btn)


        self.verticalLayout_2.addLayout(self.horizontalLayout)


        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.log_dock = QDockWidget(MainWindow)
        self.log_dock.setObjectName(u"log_dock")
        self.log_dock.setEnabled(True)
        self.log_dock_contents = QWidget()
        self.log_dock_contents.setObjectName(u"log_dock_contents")
        self.log_dock_contents.setMinimumSize(QSize(0, 100))
        self.verticalLayout = QVBoxLayout(self.log_dock_contents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.log_textedit = QTextEdit(self.log_dock_contents)
        self.log_textedit.setObjectName(u"log_textedit")

        self.verticalLayout.addWidget(self.log_textedit)

        self.log_dock.setWidget(self.log_dock_contents)
        MainWindow.addDockWidget(Qt.DockWidgetArea.BottomDockWidgetArea, self.log_dock)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1046, 37))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuWaypoint = QMenu(self.menuBar)
        self.menuWaypoint.setObjectName(u"menuWaypoint")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuDevice = QMenu(self.menuBar)
        self.menuDevice.setObjectName(u"menuDevice")
        MainWindow.setMenuBar(self.menuBar)
        self.status_bar = QStatusBar(MainWindow)
        self.status_bar.setObjectName(u"status_bar")
        MainWindow.setStatusBar(self.status_bar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.LeftToolBarArea, self.toolBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuWaypoint.menuAction())
        self.menuBar.addAction(self.menuDevice.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.import_file_action)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.save_file_action)
        self.menuFile.addSeparator()
        self.menuWaypoint.addAction(self.add_wpt_action)
        self.menuWaypoint.addAction(self.delete_wpt_action)
        self.menuView.addAction(self.toggle_debug_log_action)
        self.menuDevice.addAction(self.scan_for_devices_action)
        self.menuDevice.addSeparator()
        self.menuDevice.addAction(self.download_locations_fit_action)
        self.menuDevice.addAction(self.upload_locations_fit_action)
        self.toolBar.addAction(self.import_file_action)
        self.toolBar.addAction(self.save_file_action)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.download_locations_fit_action)
        self.toolBar.addAction(self.upload_locations_fit_action)

        self.retranslateUi(MainWindow)
        self.toggle_debug_log_action.toggled.connect(self.log_dock.setVisible)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"LocationsFITTool", None))
        self.add_wpt_action.setText(QCoreApplication.translate("MainWindow", u"Add Waypoint", None))
#if QT_CONFIG(shortcut)
        self.add_wpt_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.delete_wpt_action.setText(QCoreApplication.translate("MainWindow", u"Delete Waypoint", None))
#if QT_CONFIG(shortcut)
        self.delete_wpt_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Backspace", None))
#endif // QT_CONFIG(shortcut)
        self.toggle_debug_log_action.setText(QCoreApplication.translate("MainWindow", u"Toggle Debug Log", None))
#if QT_CONFIG(shortcut)
        self.toggle_debug_log_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+L", None))
#endif // QT_CONFIG(shortcut)
        self.scan_for_devices_action.setText(QCoreApplication.translate("MainWindow", u"Scan For Devices", None))
#if QT_CONFIG(shortcut)
        self.scan_for_devices_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.import_file_action.setText(QCoreApplication.translate("MainWindow", u"Import File", None))
#if QT_CONFIG(shortcut)
        self.import_file_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.download_locations_fit_action.setText(QCoreApplication.translate("MainWindow", u"Download", None))
#if QT_CONFIG(shortcut)
        self.download_locations_fit_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+D", None))
#endif // QT_CONFIG(shortcut)
        self.upload_locations_fit_action.setText(QCoreApplication.translate("MainWindow", u"Upload", None))
#if QT_CONFIG(tooltip)
        self.upload_locations_fit_action.setToolTip(QCoreApplication.translate("MainWindow", u"Upload Locations.fit", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.upload_locations_fit_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+U", None))
#endif // QT_CONFIG(shortcut)
        self.save_file_action.setText(QCoreApplication.translate("MainWindow", u"Save File", None))
        self.delete_wpt_btn.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.add_wpt_btn.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuWaypoint.setTitle(QCoreApplication.translate("MainWindow", u"Waypoint", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuDevice.setTitle(QCoreApplication.translate("MainWindow", u"Device", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

